name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ github.ref_name }}
      release_created: 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Extract changelog for version
        id: changelog
        run: |
          VERSION="${{ github.ref_name }}"
          # Extract the changelog section for this version
          if [ -f CHANGELOG.md ]; then
            sed -n "/## \[$VERSION\]/,/^## \[/p" CHANGELOG.md | sed '$d' > release_notes.md
          fi
          # If release_notes.md is empty, use a default message with commit info
          if [ ! -s release_notes.md ]; then
            echo "Release $VERSION" > release_notes.md
            echo "" >> release_notes.md
            echo "## Changes" >> release_notes.md
            git log --pretty=format:"- %s" -1 >> release_notes.md
            echo "" >> release_notes.md
            echo "" >> release_notes.md
            echo "See [CHANGELOG.md](https://github.com/Fightarr/Fightarr/blob/main/CHANGELOG.md) for details." >> release_notes.md
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Fightarr ${{ github.ref_name }}
          body_path: release_notes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docker:
    needs: release
    if: needs.release.outputs.release_created == 'true'
    uses: ./.github/workflows/docker.yml
    with:
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
